apiVersion: v1
kind: ServiceAccount
metadata:
 name: keda-ccu-sa
 annotations:
   eks.amazonaws.com/role-arn: arn:aws:iam::025381531841:role/pa-cop-kead-role

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-ccu-deployment
  labels:
    app: ccu-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccu-api
  template:
    metadata:
      labels:
        app: ccu-api
    spec:
      serviceAccountName: keda-ccu-sa
      containers:
        - name: container
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: QueueUrl
              value: https://sqs.us-east-2.amazonaws.com/025381531841/keda-ccu-sqs
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: 025381531841.dkr.ecr.us-east-2.amazonaws.com/tranzact/pa-cop/keda:1.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: keda-ccu-service
  labels:
    app: ccu-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ccu-api

---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-ccu-trigger-auth-aws-credentials
  labels:
    app: ccu-api
spec:
  podIdentity:
    provider: aws

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-ccu-sqs-scaledobject
  labels:
    app: ccu-api
spec:
  scaleTargetRef:
    name: keda-ccu-deployment
  pollingInterval:  25
  cooldownPeriod:   150
  minReplicaCount:  1
  maxReplicaCount:  15
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-ccu-trigger-auth-aws-credentials
    metadata:
      queueURL: https://sqs.us-east-2.amazonaws.com/025381531841/keda-ccu-sqs
      queueLength: "5"
      awsRegion: "us-east-2"
      identityOwner: operator